index.js, lib/html-to-dom-client.js, test/html-to-react.js
Resolves #7
- Fix `DOMParser` logic in the client parser
- Throw an error if the first argument for the parser is invalid (not a string)
- Add tests to check error handling
=> Fix HTML to DOM client parser

.gitignore, .npmignore, .travis.yml, package.json
Resolves #11
- Setup [Istanbul](https://github.com/gotwarlost/istanbul) as the code coverage tool
- Setup [Coveralls](https://coveralls.io) as the test coverage reporter
- Integrate Coveralls with Travis
- Ignore `coverage` directory in `.gitignore` and `.npmignore`
- `npm run cover`: Runs Istanbul and Mocha
- `npm run coveralls`: Sends coverage to Coveralls
=> Setup Istanbul and Coveralls for coverage reporting

README.md
Fix typo, improve wording, and add more badges to `README.md`.
Add the following badges:
- [NodeICO](https://nodei.co)
- [Shields](http://shields.io)
- [David](https://david-dm.org)
=> Fix typo and add more badges to README

README.md, lib/dom-to-react.js, test/data.json, test/dom-to-react.js, test/helpers/index.js, test/html-to-react.js
Fixes #14
- The parser converts void elements like `<img>` into DOM nodes like below:
```js
{
type: 'tag',
name: 'img',
attribs: {},
children: [], // should be `null`
next: null,
prev: null,
parent: null
}
```
- So when `React.createElement('img', {}, [])` is called, it gives the following error:
```
Invariant Violation: img is a void element tag and must neither have `children`
nor use `dangerouslySetInnerHTML`.
```
- If there are [no child nodes](https://github.com/remarkablemark/html-react-parser/blob/e3c91acc3a0718a49d442181546fe0baff9645ed/lib/dom-to-react.js#L63), then make sure `children` remains `null`
- Pass `key` as the 2nd parameter to [replace](https://github.com/remarkablemark/html-react-parser/blob/e3c91acc3a0718a49d442181546fe0baff9645ed/lib/dom-to-react.js#L31). This …
=> Fix void element bug and add `key` parameter to `replace` method

.eslintrc, README.md, lib/dom-to-react.js, test/html-to-react.js
Continuation of #16
The previous fix to mitigate the [React unique keys warning](https://fb.me/react-warning-keys) was to pass the `key` as the 2nd parameter in the `replace` method.
However, this burdens users with the extra work and responsibility to set the "key" prop on their custom React element.
The smarter approach done in this pull request was to use [React.cloneElement](https://facebook.github.io/react/docs/top-level-api.html#react.cloneelement) to clone the user's custom React element and merge the key prop for them (when applicable).
- Remove the `key` parameter in `replace` method in `README.md`
- Update `.eslintrc`
=> Remove `key` parameter from `replace` and use `React.cloneElement` instead

lib/dom-to-react.js, test/data.json, test/dom-to-react.js, test/html-to-react.js
Fixes #19
- Ensure empty `<script>` tag is converted to a React element and not an empty array `[]`
- Add missing logic for parsing `<style>` DOM nodes to React element
- Update tests and mocks
=> Fix parsing of <script> and <style> tags

README.md
Add example to `README.md` to show use case where `children` needs to be kept or has its own handler in the `replace` method.
=> Update README with advanced usage of `replace` method

README.md
- Try to follow the 80 column rule for readability.
- Reword sentences to make them more understandable.
- Gives thanks to `htmlparser2` and contributors.
- Add lint script to testing documentation.
=> Tidy and reword README for readability and add contributors

.gitignore, index.js, package.json, webpack.config.js
As an improvement of #6, let [webpack](https://webpack.github.io) handle building the [UMD bundle](https://webpack.github.io/docs/library-and-externals.html). Build inspired by [react-router](https://github.com/ReactTraining/react-router/blob/master/webpack.config.js).
The bundle will be generated in the `./dist/` directory as `html-react-parser.js` and `html-react-parser.min.js`.
- Create npm scripts:
- `build`: Builds development/unminified bundle
- `build-min`: Builds production/minified bundle
- `prepublish`: Runs `build` and `build-min` before publish
- Save `webpack@1.13.2` and create `webpack.config.js`
- Add `dist` to `.gitignore`
=> Use webpack to build UMD bundle

lib/html-to-dom-client.js, test/html-to-dom.js
Fixes #23
- Fix regex so that only the tag name is matched for the client parser before being parsed by `window.DOMParser`
- Add test to ensure client parser does not break on regex and `DOMParser`
=> Fix regex bug on client parser

.npmignore, package.json
- Rename dist output filenames:
- `./dist/html-to-react.js` => `./dist/html-react-parser.js`
- `./dist/html-to-react.min.js` => `./dist/html-react-parser.min.js`
- Add `webpack.config.js` to `.npmignore`
The published contents are now viewable on https://unpkg.com/html-react-parser/
=> Rename dist filenames and add webpack to `.npmignore`

lib/DOMPropertyConfig.js, lib/attributes-to-props.js, lib/property-config.js
Both `HTMLDOMPropertyConfig.js` and `SVGDOMPropertyConfig.js` used to be in `react/lib/` directory but since v15.4.x, the configs have been moved to `react-dom/lib/`.
Created a module that tried to require either `react-dom/lib/` or `react/lib/` (fallback).
A more permanent (less error-prone) solution may be to keep a hardcopy of both configs in the repository (minimize coupling and risk of another change from breaking the package).
Update travis to test react and react-dom versions `15.3` and `15.4`.
Fixes #29
=> Fix bug due to DOMPropertyConfigs being moved to `react-dom` in v15.4

lib/property-config.js, package.json
Following step after #31
This will hopefully support react latest as long as there are no more breaking changes. This will bump the package to `0.3.0`
Update `devDependencies` and `peerDependencies` in `package.json` to use `react` and `react-dom` `>=15.4`
=> Require DOM property configs from `react-dom/lib/` in react >=15.4

index.js, test/html-to-react.js
HTML entities aren't decoded by default for `htmlparser2` (initialized by `html-dom-parser`). As a result, this will lead to an `Invariant Violation` because the entities are decoded on the client-side.
The fix is to always set `decodeEntities: true` for `htmlparser2`.
Resolves #34.
- Set parser options `decodeEntities` to true for `html-dom-parser`, which gets passed to `htmlparser2`
- Write test to confirm that HTML entities passed to React element's children are properly decoded
=> Decode HTML entities by default on node

examples/requirejs.html, examples/script-tag.html, package.json
- Update examples to load parser from relative `dist/` directory as this ensures the parser is the current version after running build
- Remove **"browser"** field from `package.json` since `html-dom-parser` handles it in its own package
=> Update examples and package.json

CHANGELOG.md, package.json
Resolves #39
- dependencies:
- html-dom-parser@0.1.0
- devDependencies:
- coveralls@2.13.1
- eslint@4.0.0
- mocha@3.4.2
- webpack@2.6.1
=> Upgrade dependencies (html-dom-parser@0.1.0)

CHANGELOG.md, README.md, examples/requirejs.html, examples/script-tag.html, lib/property-config.js, package.json, test/helpers/mocks.json
Resolves #43
Because `react-dom` v16 no longer exposes `lib` (see [issue](https://github.com/facebook/react/issues/10391)), which includes the DOM property configs, [react-dom-core](https://github.com/remarkablemark/react-dom-core) is used as an alternative.
=> Add `react-dom-core` to support react-dom@16

lib/attributes-to-props.js, lib/utilities.js, package.json, test/attributes-to-props.js
When we have a style attribute on the original HTML, the parsing was not correct, specially with background-image with an external URL, this was not loading because of a split by ':' what breaks the URL. I added an library that generates a more complete style tag using css-to-react-native.
=> Fix component style attribute parser

index.js, test/dom-to-react.js, test/helpers/mocks.json
The implementation assumes all attributes are lowercase, this [isn't the case for SVGs](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/svg#Specific_attributes). As a result when trying to map attributes to props the `viewBox` attribute breaks. 
https://unpkg.com/react-dom@15.6.2/lib/SVGDOMPropertyConfig.js
=> Some SVG attributes aren't correctly handled, for example viewBox

lib/attributes-to-props.js, lib/dom-to-react.js, lib/utilities.js, test/attributes-to-props.js, test/dom-to-react.js, test/helpers/data.json, test/utilities.js
Closes https://github.com/remarkablemark/html-react-parser/issues/77
=> feat: support custom elements in React 16

lib/dom-to-react.js, test/dom-to-react.js
In current implementation when you use dom-to-react with replace option created elements usually have keys generated from index of node, even if component in replace have it's own key. 
According to https://fb.me/react-warning-keys 
"We don’t recommend using indexes for keys if the order of items may change. This can negatively impact performance and may cause issues with component state. "
In our case it cause problems with performance. 
This pull request will allow using keys from replacement components (for example id of element can be used as key if put it as key to component returned by replace).
=> DomToReact: Allow custom keys for replacement

README.md
Better documentation
Currently, the code sample in the README makes reference to a variable called `parserOptions`, even though that variable does not exist within the sample.
It seems that this variable is actually a reference to the object that contains the `replace` method, and that object should get passed in as the second argument to the calls to `domToReact`.
The new code sample creates a constant called `parserOptions`, which can then be passed as the second argument to `domToReact`.
Thanks!
=> update code sample in README

README.md, package.json
The latest version helps decrease the library's bundle size given the optimizations in remarkablemark/style-to-object#5:
|                | unminified    | minified |
| -------------- | ------------- | -------- |
| with css@0.2.2 | 71.3 kB       | 21.9 kB  |
| with css@0.2.3 | 67.9 kB       | 19.7 kB  |
Tidy and update `README.md`
=> build(package): update dependency `style-to-object` to 0.2.3

README.md, lib/attributes-to-props.js, lib/dom-to-react.js, package.json, test/dom-to-react.js, test/helpers/data.json, test/html-to-react.js
=> fix: revert commit so <script> is parsed or else server-side rendering breaks

README.md
Changed `parserOptions` to `options` in the longest example.
Fixes #122
=> docs(readme): change parserOptions to options in longest example

package.json
```
html-dom-parser    0.2.2  →   0.2.3
```
This fixes a bug related to client-side DOM parsing for unclosed HTML markup.
Relates to #126 and remarkablemark/html-dom-parser#18
=> build(package): upgrade dependency html-dom-parser@0.2.3

README.md, index.d.ts, lib/dom-to-react.js, package.json, test/dom-to-react.js
Support using Preact instead of React
Only React is supported
New option `library` is added to allow using Preact
As far as I'm aware, NPM doesn't allow specifying multiple packages that can satisfy a single peer dependency (i.e. warn if neither React or Preact are missing, but satisfy if one is present) - so I've used an unofficial option `optionalPeerDependencies`. Alternatively, `package.json` could be left as-is, assuming most people will want React.
=> Add support for Preact

index.d.ts, lib/dom-to-react.js
Fixes `index.d.ts` by making `replace` property optional in the 2nd argument object.
Also, updated and fixed incorrect JSDoc in `lib/dom-to-react.js`.
If a 2nd argument is specified, `replace` is required so instead of:
```js
{ replace: undefined }
```
Developers are forced to:
```js
{ replace: () => {} }
```
See #134
Developers are no longer forced to satisfy the type requirements. See above.
=> fix: make `replace` optional in type declaration and update JSDoc

index.d.ts, lib/dom-to-react.d.ts, test/types/index.test.tsx, test/types/lib/dom-to-react.test.tsx
This makes the library usable for non-React JSX implementations in TypeScript. JSX.Element is defined as React.ReactElement for the 'react' package, and is [overridden by other JSX implementations](https://devblogs.microsoft.com/typescript/announcing-typescript-2-8-rc/). Fixes #145.
Currently, trying to use html-react-parser with Preact in TS will result in a bunch of type errors.
* React.ReactElement is replaced with JSX.Element, which aliases to React.ReactElement for the current tests
* The HTMLReactParser return value matches the domToReact return value, since the former returns the output of the latter
=> fix: use JSX.Element for type definitions

.eslintrc.json, index.d.ts, index.js, lib/dom-to-react.d.ts, package.json, test/attributes-to-props.js, test/dom-to-react.js, test/html-to-react.js, test/types/index.test.tsx, test/types/lib/dom-to-react.test.tsx
- Improve parser types (options.library)
- Fix dtslint
- Use early return for empty string (performance optimization)
- Tidy tests
=> refactor: improve parser types

README.md, index.d.ts, index.js, package.json, test/html-to-react.js, test/types/index.test.tsx
feature
- add option `htmlparser2`
Closes #158
No way to pass options to `html-dom-parser`, which uses `htmlparser2` on Node.js (server-side)
Ability to pass options to `htmlparser2` from library options
=> feat: add option htmlparser2

README.md, index.d.ts, lib/dom-to-react.js, test/html-to-react.js, test/types/index.test.tsx, test/types/lib/dom-to-react.test.tsx
Feature: add option `trim`.
Resolves #155
There is no way to remove whitespace text nodes.
By passing option `{ trim: true }`, whitespace text nodes are skipped:
```js
parse('<br>\n', { trim: true }) // React.createElement('br')
```
This helps resolve the warning:
```
Warning: validateDOMNesting(...): Whitespace text nodes cannot appear as a child of <table>. Make sure you don't have any extra whitespace between tags on each line of your source code.
```
=> feat: add option `trim`

README.md
docs: update FAQ with how to prevent tags from being lowercased
See #62
N/A
N/A
=> docs(readme): update FAQ with how to preserve case of tags (#62)

README.md, index.d.ts, index.js, lib/attributes-to-props.d.ts, test/helpers/data.js, test/html-to-react.test.js
sometimes we need custom the replacer, and so we maybe need the attributesToProps too.
Users need to implement it themselves
just require the `attributesToProps` function
=> feat: export attributesToProps

package.json, rollup.config.js
Fix [Travis CI build error](https://travis-ci.org/github/remarkablemark/html-react-parser/jobs/739476952) when installing with npm 7:
```sh
$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: rollup@2.32.1
npm ERR! node_modules/rollup
npm ERR!   dev rollup@"^2.12.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer rollup@">=0.66.0 <2" from rollup-plugin-uglify@6.0.4
npm ERR! node_modules/rollup-plugin-uglify
npm ERR!   dev rollup-plugin-uglify@"^6.0.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
To resolve …
=> build(rollup): replace rollup plugin uglify with terser

package.json
The library currently does not list React 17 as peer dependency
=> List React 17 as peer dependency

lib/attributes-to-props.js, lib/utilities.js, package.json, test/__snapshots__/attributes-to-props.test.js.snap, test/attributes-to-props.test.js, test/utilities.test.js
refactor: replace `cssToJs` with `style-to-js` and remove `camelCase`. See #177
bug fix: parse style with vendor prefix `-khtml-` (Konqueror, really old Safari). See remarkablemark/style-to-js#1
Cannot make use of [`cssToJs`](https://github.com/remarkablemark/html-react-parser/blob/4b5fad9ca5ea47d360a1b894ed0f675f879d7f65/lib/attributes-to-props.js#L76) function
Can install [`style-to-js`](https://github.com/remarkablemark/style-to-js) and use with library:
```js
const htmlReactParser = require('html-react-parser');
const styleToJS = require('style-to-js').default;
// ...
```
=> refactor: replace `cssToJs` with `style-to-js` and remove `camelCase`

lib/dom-to-react.js, test/__snapshots__/dom-to-react.test.js.snap
fix(dom-to-react): transform style to object for Web Components
Fixes #188
[Web Components](https://reactjs.org/docs/web-components.html) skip the `attributesToProps` process. However, React still expects the custom element `style` prop to be an object and not a string:
```
Error: The `style` prop expects a mapping from style properties to values, not a string. For example, style={{marginRight: spacing + 'em'}} when using JSX.
```
Web Components will only get the `style` attribute transformed into an object.
=> fix(dom-to-react): transform style to object for Web Components

index.d.ts, lib/attributes-to-props.d.ts, lib/dom-to-react.d.ts, lib/dom-to-react.js, package.json, test/types/index.tsx, test/types/lib/dom-to-react.tsx
build(package): upgrade dependency `html-dom-parser` to 0.5.0
```
html-dom-parser  0.3.0  →  0.5.0
```
This is a **BREAKING CHANGE** because upgrading `domhandler@3.3.0` and `htmlparser2@4.1.0` will cause types to change.
dependencies:
- [`html-dom-parser`@0.3.0](https://github.com/remarkablemark/html-dom-parser/releases/tag/v0.3.0)
dependencies:
- [`html-dom-parser`@0.5.0](https://github.com/remarkablemark/html-dom-parser/releases/tag/v0.5.0)
- `@types/htmlparser2` (removed)
=> build(package): upgrade dependency `html-dom-parser` to 0.5.0

.github/workflows/size-limit.yml, .size-limit.json, README.md, package.json
ci(github): add `size-limit.yml` workflow
No way to test bundle size or performance.
Added [Size Limit GitHub Action](https://github.com/marketplace/actions/size-limit-action), which uses [Size Limit](https://github.com/ai/size-limit) to calculate cost of JavaScript bundle for end-users.
The bundle size `limit` is set to `8 KB`.
=> ci(github): add `size-limit.yml` workflow

README.md, index.d.ts, test/types/index.tsx, tslint.json
feat(index): export `domhandler` node types and update `README.md`
`domhandler` node types not exported. Thus, users have to import directly from `domhandler` (see #199):
```ts
import { Element } from 'domhandler/lib/node';
```
`domhandler` node types exported:
```ts
import parse, { Element } from 'html-react-parser';
```
=> feat(index): export `domhandler` node types and update README.md

README.md, index.js, package.json, test/__snapshots__/index.test.js.snap, test/data/html.js, test/index.test.js
fix: escape tags inside of `<title>`
Fixes #202
Tags inside of `<title>` are not escaped.
Tags inside of `<title>` are escaped by upgrading to [html-dom-parser@1.0.0](https://github.com/remarkablemark/html-dom-parser/releases/tag/v1.0.0).
```
html-dom-parser  0.5.0  →  1.0.0
```
=> fix: escape tags inside of <title> (upgrade html-dom-parser to 1.0.0)

index.d.ts, test/types/index.tsx, test/types/lib/dom-to-react.tsx
Fixes #207
fix(index): include domhandler `Node` in `DOMNode` type
```ts
import {
Comment,
DomHandlerOptions,
Element,
ProcessingInstruction,
Text
} from 'domhandler';
export { Comment, Element, ProcessingInstruction, Text };
export type DOMNode = Comment | Element | ProcessingInstruction | Text;
```
```ts
import {
Comment,
DomHandlerOptions,
Element,
Node,
ProcessingInstruction,
Text
} from 'domhandler';
export { Comment, Element, Node, ProcessingInstruction, Text };
export type DOMNode = Comment | Element | Node | ProcessingInstruction | Text;
```
=> fix(index): include domhandler `Node` in `DOMNode` type

index.mjs, package.json
I had installed `html-react-parser` in a project using Snowpack, but found I could only access the default export, and not `domToReact`, `htmlToDOM` or `attributesToProps`.
[Snowpack](https://github.com/snowpackjs/snowpack) - which uses [esbuild](https://github.com/evanw/esbuild) internally - creates native ES module bundles which can be directly imported from the browser. Due to the way `html-react-parser` exports its modules, the following lines:
```js
// support CommonJS and ES Modules
module.exports = HTMLReactParser;
module.exports.default = HTMLReactParser;
```
were being converted into:
```js
// support CommonJS and ES Modules
var htmlReactParser = HTMLReactParser;
var _default = HTMLReactParser;
htmlReactParser.default = _default;
export default htmlReactParser;
```
...because …
=> Improve support for modern ESM build tools

.github/workflows/build.yml, package.json, test/integration/index.test.js
test: add integration tests for UMD bundle and fail build if there are warnings
- No integration tests for UMD bundle
- Rollup build does not fail if there are warnings
- Added integration tests for UMD bundle
- Rollup build fails if there are warnings
=> test(integration): add tests for UMD bundle and fail build if there are warnings

index.mjs
Fixes #214, fixes #213
fix(index): export without const in `index.mjs`
Module bundlers (webpack, rollup) that prioritizes the `module` field in `package.json` is now getting bundling `const` (introduced in #210) because of the syntax:
```js
import HTMLReactParser from './index.js';
export default HTMLReactParser;
export const { domToReact, htmlToDOM, attributesToProps } = HTMLReactParser;
```
This breaks older/legacy browsers like IE11.
Update `index.mjs` to export without `const`:
```js
export { default, domToReact, htmlToDOM, attributesToProps } from './index.js';
```
=> fix(index): export without const in `index.mjs`

index.mjs
Fixes #217
fix(index): make sure to export the named exports
#216 caused a regression where the named exports are not working:
```
./node_modules/html-react-parser/index.mjs
Can't reexport the named export 'attributesToProps' from non EcmaScript module (only default export is available)
```
Reverted `index.mjs` back to how it was before but replaced `const` with `var`:
```js
import HTMLReactParser from './index.js';
export default HTMLReactParser;
export var { domToReact, htmlToDOM, attributesToProps } = HTMLReactParser;
```
=> fix(index): make sure to export the named exports

index.mjs
Fixes #222
fix(index): refactor ES module from ES6 to ES5 syntax
This is a regression from #220
The ES module `index.mjs` uses ES6 syntax (object destructuring assignment), which breaks older browsers like IE11.
`index.mjs` uses ES6 syntax.
=> fix(index): refactor ES module from ES6 to ES5 syntax

package.json
added missing dependency for "domhandler": "^4.0.0"
fixes #231
Explanation can be found in the issue. Only tested the workaround explained in the issue.
=> fix(package): add domhandler to dependencies

lib/attributes-to-props.d.ts, test/types/lib/attributes-to-props.ts, tsconfig.json
Fixes #242
fix(attributes-to-props): fix attributes-to-props type `Props`
```ts
type Props = Record<string, string>;
```
```ts
type Props = Record<string, string> & {
style: Record<string, string>;
}; 
```
=> fix(attributes-to-props): fix attributes-to-props type `Props`

lib/utilities.js, test/index.test.js, test/utilities.test.js
=> fix(utilities): skip invalid style attributes

.github/workflows/build.yml
ci(github): use default Node.js version in `build.yml`
Node.js version is hardcoded.
Use default Node.js version (LTS).
=> ci(github): use default Node.js version in `build.yml`

lib/attributes-to-props.js, package.json, test/__snapshots__/attributes-to-props.test.js.snap, test/attributes-to-props.test.js
Relates to https://github.com/remarkablemark/react-dom-core/issues/14
feat: upgrade `react-property` to get react-dom 17 DOM/SVG properties
Uses DOM/SVG properties from react-dom 15
Uses DOM/SVG properties from react-dom 17
=> feat: upgrade `react-property` to get react-dom 17 DOM/SVG properties

.size-limit.json, package.json
ci(size-limit): increase limit from 8 to 9.23 KB
Size Limit is set at 8 KB and failing with v1.3.0 release
Increase Size Limit to 9.23 KB
=> ci(size-limit): increase limit from 8 to 9.23 KB

package.json
Upgrade `html-dom-parser` to [1.0.3](https://github.com/remarkablemark/html-dom-parser/releases/tag/v1.0.3)
```
html-dom-parser  1.0.2  →  1.0.3
```
See https://github.com/remarkablemark/html-dom-parser/pull/146
=> perf: upgrade dependency html-dom-parser to v1.0.3

.size-limit.json, package.json
build(deps): bump `domhandler` to 4.3.0 and `html-dom-parser` to 1.0.4
Closes #372
```
domhandler       4.2.2  →  4.3.0
html-dom-parser  1.0.3  →  1.0.4
```
=> build(deps): bump domhandler to 4.3.0 and html-dom-parser to 1.0.4

README.md, lib/dom-to-react.js, lib/utilities.js, test/index.test.js, test/utilities.test.js
Fixes #384
Fixes an issue #384 where trimming can lead to inaccurate parsing when nodes have whitespace characters
- if trim is off, whitespace characters trigger reacts validation errors
- if trim is on, whitespaces are stripped from nodes that can contain white spaces which results in inaccurate parsing
Regardless of the trimming setting, if a text node appears in a node that can contain text nodes eg `<table>`, `<tr>`, it will be removed. If trimming is off, then whitespaces are preserved in nodes that can contain text nodes. 
Looking for approvals before I add to documentation!
=> fix: trim only when necessary if trimming is off

package.json
=> fix: add exports main field

package.json
build(package): upgrade html-dom-parser from 1.0.4 to 1.1.0
See https://github.com/remarkablemark/html-dom-parser/issues/181 and https://github.com/remarkablemark/html-dom-parser/pull/202
html-dom-parser is 1.0.4
html-dom-parser is 1.1.0
=> build(package): upgrade html-dom-parser from 1.0.4 to 1.1.0

index.js, test/index.test.js
Fixes #445
fix: support backwards compatibility for `html-dom-parser`'s ES Module
Regression was caused in [1.4.7](https://github.com/remarkablemark/html-react-parser/releases/tag/v1.4.7). Related to https://github.com/remarkablemark/html-dom-parser/pull/202
next@10 throws an error:
```
TypeError: htmlToDOM is not a function
```
Note: next@11 and 12 did not have this error
No error in next@10
=> fix: ensure backwards compatibility for html-dom-parser's ES Module

package.json
Closes #511
build: upgrade html-dom-parser to add support for react-native
```
html-dom-parser  1.1.1  →  1.2.0
```
See https://github.com/remarkablemark/html-dom-parser/pull/246
html-dom-parser v1.1.1
html-dom-parser v1.2.0
=> build: upgrade html-dom-parser to add support for react-native

package.json
Fix warning with package when running react-native
bug fix
https://github.com/react-native-community/cli/issues/1168 - When running react-native under Node.js 14.x on a project that uses npm modules which specify the new exports field in package.json, react-native will throw a warning of 
`warn Package html-react-parser has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /PATH_TO_CURRENT_PROJECT/node_modules/html-react-parser/package.json`
Warning no longer appears and package runs correctly
=> fix: package.json not defined by exports warning

.size-limit.json, index.js
Fix error  when running with webpack build
bug fix
Got Module Not Found error `Package path ./lib/node is not exported from package ..../node_modules/domhandler`
I found the related issue https://github.com/remarkablemark/html-react-parser/issues/252#issuecomment-896406971  and pr  https://github.com/remarkablemark/html-react-parser/pull/296 , which exports the `Element `type of `domhandler`.
But `domhandler` has used `exports` field,  only exports index files  https://github.com/fb55/domhandler/blob/master/package.json#L13
```
"exports": {
"require": "./lib/index.js",
"import": "./lib/esm/index.js"
},
```
Require `Element` directly from 'domhandler' index.
Error no longer appears and webpack build runs correctly
=> fix: export domhandler' Element from it's exports field

.size-limit.json, package.json, test/attributes-to-props.test.js
Relates to https://github.com/remarkablemark/style-to-js/issues/2, https://github.com/remarkablemark/style-to-js/pull/3
fix: don't capitalize `-ms` vendor prefix
[style-to-js@1.1.0](https://github.com/remarkablemark/style-to-js/releases/tag/v1.1.0) capitalizes `-ms` vendor prefix
[style-to-js@1.1.1](https://github.com/remarkablemark/style-to-js/releases/tag/v1.1.1) doesn't capitalize `-ms` vendor prefix
=> fix: bump `style-to-js` to 1.1.1; don't capitalize `-ms` vendor prefix

README.md, package.json
BREAKING CHANGE: drop Internet Explorer (IE) support
Internet Explorer has been retired on 2022-06-15
See https://github.com/remarkablemark/html-dom-parser/pull/302
IE11 is still supported
IE is no longer supported
=> build(package): bump html-dom-parser from 1.2.0 to 2.0.0 

README.md, package.json, test/types/index.tsx, test/types/lib/dom-to-react.tsx
Relates to https://github.com/remarkablemark/html-dom-parser/pull/314
BREAKING CHANGE: bump `domhandler` from 4 to 5 and `html-dom-parser` from 2 to 3
```
domhandler       4.3.1  →  5.0.3
html-dom-parser  2.0.0  →  3.0.0
```
- domhandler@4.3.1
- html-dom-parser@2.0.0
- domhandler@5.0.3
- html-dom-parser@3.0.0
=> build: upgrade domhandler to 5.0.3 and html-dom-parser to 3.0.0

package.json
Fixes #624
- fix: parse head/body with newline correctly
- build(package): bump html-dom-parser from 3.0.0 to 3.0.1
- html-dom-parser@3.0.0
- head/body elements with newline are not parsed correctly
- html-dom-parser@3.0.1
- head/body elements with newline are parsed correctly
=> fix: parse head/body with newline correctly (bump html-dom-parser)

package.json, test/index.test.js
build(package): bump html-dom-parser from 3.0.1 to 3.1.0
Closes #655
html-dom-parser@3.0.1
[html-dom-parser@3.1.0](https://github.com/remarkablemark/html-dom-parser/pull/332#issuecomment-1216102243)
See https://github.com/remarkablemark/html-dom-parser/pull/331
=> build(package): bump html-dom-parser from 3.0.1 to 3.1.0

package.json
fix(package): upgrade html-dom-parser to fix client ES Module export
See https://github.com/remarkablemark/html-dom-parser/pull/335
```
ReferenceError: module is not defined
```
No ReferenceError
=> fix(package): upgrade html-dom-parser to fix client ES Module export

package.json
fix(package): upgrade html-dom-parser to fix client ES Module import
Fixes #662
Relates to https://github.com/remarkablemark/html-dom-parser/issues/337
Error in html-dom-parser@3.1.1:
```
error - /app/node_modules/html-dom-parser/lib/client/html-to-dom.mjs
Can't import the named export 'formatDOM' from non EcmaScript module (only default export is available)
```
No error in [html-dom-parser@3.1.2](https://github.com/remarkablemark/html-dom-parser/pull/339#issuecomment-1223371393)
=> fix(package): upgrade html-dom-parser to fix client ES Module import

.size-limit.json, index.d.ts, index.js, index.mjs, test/index.test.js, test/integration/index.test.js, test/module/index.mjs
fix(index): export domhandler classes
Fixes #777
Only `domhandler` class Element is exported
Export additional `domhandler` classes:
- Comment
- ProcessingInstruction
- Text
=> fix(index): export domhandler classes

package.json
- fix(package): include types in exports to support TypeScript ESM node16
- build(package): bump style-to-js from 1.1.2 to 1.1.3 
- build(package): bump html-dom-parser from 3.1.2 to 3.1.3
=> fix(package): include types in exports to support TypeScript ESM node16

index.js
fix(index): fix exports for UMD build (CDN script)
Fixes #828
CDN (UMD) script throws error:
```
Uncaught ReferenceError: exports is not defined
```
No error when loading by script
=> fix(index): fix exports for UMD build (CDN script)

package.json
Bump html-dom-parser from 3.1.3 to 3.1.4 in order to fix template parsing
Fixes #849
Unable to parse template childNodes
Template children parsed correctly
=> fix: upgrade `html-dom-parser` to 3.1.4 in order to fix template parsing

.size-limit.json, lib/attributes-to-props.js, test/attributes-to-props.test.js, test/data/html.js, test/index.test.js
fix(attributes-to-props): don't convert non-uncontrolled component props
Fixes #839
Non-uncontrolled component (e.g., `<li>`) attributes like `value` are being converted to `defaultValue` which is incorrect
Only uncontrolled components have attributes `checked` and `value` converted:
- `<input>`
- `<select>`
- `<textarea>`
Non-uncontrolled components are ignored
=> fix(attributes-to-props): don't convert non-uncontrolled component props

package.json
Fixes #855
Parse error:
```js
import parse from 'html-react-parser';
parse('<meta name="author" content="John Doe Mason" />');
```
```
TypeError: Cannot read properties of undefined (reading 'length')
at formatDOM (lib/client/utilities.js)
```
No error
=> fix(package): bump html-dom-parser@3.1.5 to fix formatDOM error

package.json
fix: bump html-dom-parser to 3.1.6 to fix feGaussianBlur misspelling
Fixes #734
Relates to #429 and #430
```
feGaussainBlur
```
```
feGaussianBlur
```
=> fix: bump html-dom-parser to 3.1.6 to fix feGaussianBlur misspelling

index.d.ts, lib/attributes-to-props.d.ts, lib/dom-to-react.d.ts, tslint.json
fix(types): fix `Type error: ',' expected.` in index.d.ts
Fixes #871
Some TypeScript users are getting the error:
```
../../node_modules/html-react-parser/index.d.ts:10:8
Type error: ',' expected.
```
This is caused by module and type imports from 'domhandler' being combined into one.
Separated module and type imports.
=> fix(types): fix `Type error: ',' expected.` in index.d.ts

package.json
Release-As: 3.0.15
```
html-dom-parser. 3.1.6  →  3.1.7
```
https://github.com/remarkablemark/html-dom-parser/pull/435
=> build(package): bump html-dom-parser from 3.1.6 to 3.1.7

README.md
To fix a "erorr" typo and sentence with "to be" in README.md I found while reading the docs.
It's my first contribution to open-source; I hope it helps! 😄 
=> docs(readme): fix 2 typos in README.md

README.md, package-lock.json, package.json
BREAKING CHANGE: bump html-dom-parser from 3.1.7 to 4.0.0
Closes https://github.com/remarkablemark/html-react-parser/pull/941
https://github.com/remarkablemark/html-dom-parser/releases/tag/v4.0.0
=> build(deps): bump html-dom-parser from 3.1.7 to 4.0.0

README.md, index.d.ts, lib/dom-to-react.js, lib/utilities.js, test/dom-to-react.test.js
My use case is as follows:
```tsx
function Wrapper({ node, children }) {
const [show, setShow] = useState(false)
return <>
{show && children}
<button onClick={() => setShow(s => !s)}>Toggle</button>
</>
}
domToReact(nodes, {
transform(node, reactNode) {
return <Wrapper node={node}>{reactNode}</Wrapper>
}
})
```
I want to wrap every element in a Wrapper. I don't think this is possible with `replace` as it "replaces" the elements, not wraps them, and I can't easily "pass through" the subtree.
If you think this PR is worth considering I will follow up with tests and extra documentation.
=> feat: add transform option

package.json
This exposes the lib files, so `domToReact` can be imported without importing all of `domhandler`, which reduces bundle size.
It also exposes `attributesToProps`, which is useful (at least in my project)
You can import like `import domToReact from 'html-react-parser/dom-to-react'` and `import attributesToProps from 'html-react-parser/attributes-to-props'`
=> feat: export lib files

lib/utilities.js
@remarkablemark 😂
I forgot to change the location of the jsdoc in the pull request yesterday, sorry🙏
I've repositioned it and added the missing jsdoc.
There is no change in behavior.
There is no change in behavior.
=> refactor(utilities): adding a jsdoc and reverting an existing jsdoc location

.size-limit.json, index.js, package-lock.json, package.json, test/dom-to-react.test.js, test/index.test.js
Release-As: 4.2.4
build(package): bump html-dom-parser from 4.0.1 to 5.0.0
[html-dom-parser v4.0.1](https://github.com/remarkablemark/html-dom-parser/releases/tag/v4.0.1)
[html-dom-parser v5.0.0](https://github.com/remarkablemark/html-dom-parser/releases/tag/v5.0.0)
=> build(package): bump html-dom-parser from 4.0.1 to 5.0.0

package-lock.json, package.json
fix: upgrade html-dom-parser and style-to-js to fix source map warnings
Fixes #1097
```
html-dom-parser  5.0.1  →  5.0.2
style-to-js      1.1.6  →  1.1.8
```
Source map warnings
No source map warnings
=> fix: upgrade `html-dom-parser` and `style-to-js` to fix source map warnings

lib/utilities.js, test/utilities.test.js
chore(utilities): remove unused function `invertObject`
Release-As: 4.2.8
=> chore(utilities): remove unused function `invertObject`

index.d.ts, lib/attributes-to-props.d.ts, lib/dom-to-react.d.ts, package-lock.json, package.json
Release-As: 4.2.9
```
react-property   2.0.0  →  2.0.2
```
=> build(package): bump `react-property` from 2.0.0 to 2.0.2

__tests__/dom-to-react.test.tsx, src/dom-to-react.ts
fix(dom-to-react): default props.children to undefined instead of null
props.children defaults to `null`. E.g., `parse('<br>')`:
```js
{
'$$typeof': Symbol(react.element),
type: 'br',
key: null,
ref: null,
props: { children: null },
_owner: null,
_store: {}
}
```
props.children defaults to `undefined`
This ensures the parsed element is consistent with the React element `<br >`:
```js
{
'$$typeof': Symbol(react.element),
type: 'br',
key: null,
ref: null,
props: {},
_owner: null,
_store: {}
}
```
=> fix(dom-to-react): default props.children to `undefined` instead of `null`

__tests__/dom-to-react.test.tsx, src/types.ts
fix(types): add back `object` to `replace` option return type
Maintains backward compatibility for invalid return type
Fixes #1126
Removed `object` return type from `replace` option in v5
Revert removal of `object` return type from `replace` option
=> fix(types): add back `object` to `replace` option return type

esm/attributes-to-props.mjs, esm/dom-to-react.mjs, esm/index.mjs
fix(esm): support vite bundler
Fixes #1132
Running `npx vite build && npx vite preview` throws an error in the browser:
```
TypeError: rm is not a function
```
Fix the default export so that vite builds properly
=> fix(esm): support vite bundler

README.md
@remarkablemark 
I'm very happy to contribute to that library! Thanks again for providing such a great library 🤗
How about changing `Contributors` in the `README.md` from `opencollective` to [contrib.rocks](https://contrib.rocks/preview?repo=angular%2Fangular-ja) since it doesn't seem to be up to date? 😂 
<br />
You can use the `max` and `columns` options if you need to!
```
https://contrib.rocks/image?repo=remarkablemark/html-react-parser&max=10&columns=10
```
=> docs(readme): modify contributors img in the README

esm/attributes-to-props.d.mts, esm/dom-to-react.d.mts, esm/index.d.mts, esm/index.mjs, esm/utilities.d.mts, esm/utilities.mjs, package.json
fix(esm): fix ESM types by adding .mts declaration files
No `.mts` files in `esm` directory
`.mts` files in `esm` directory
=> fix(esm): fix ESM types by adding .mts declaration files

.commitlintrc.json, esm/index.mjs, esm/utilities.mjs
Fixes #1228
Caused by #1226
Vite fails with the error:
```
Uncaught SyntaxError: The requested module '/@fs/Users/.../node_modules/.vite/app/deps/html-react-parser.js?v=719515aa' does not provide an export named 'Element' (at list.tsx:6:31)
```
`*` exports in ESM files
Vite does not error
Named exports in ESM files
=> fix(esm): make ESM exports explicit in index.mjs and utilities.mjs

README.md, __tests__/dom-to-react.test.tsx, src/dom-to-react.ts, src/types.ts
feat(dom-to-react): pass index as 2nd argument to `replace` option
Closes #1240
`replace` option has 1 argument: `domNode`
`replace` option has 2 arguments: `domNode` and `index`
=> feat(dom-to-react): pass index as 2nd argument to `replace` option

src/dom-to-react.ts, src/types.ts
Release-As: 5.1.2
@remarkablemark  👋
```tsx
function attributesToProps(attributes?: Attributes, nodeName?: string): Props
export default function attributesToProps(
attributes: Attributes = {},
nodeName?: string,
)
```
What do you think about utilizing the same default parameters as `attributes`? 
We can remove optional chaining ..!! 
I think it's clearer to specify the type of `rest parameter` as an array. 
There is no change in behavior
There is no change in behavior
=> refactor: improved dom-to-react, type

__tests__/dom-to-react.test.tsx, esm/index.d.mts, src/dom-to-react.ts, src/index.ts, src/types.ts
fix(esm): fix exported types
Fixes #1305
1. ESM types not working
2. Using global `JSX` namespace
1. ESM types working
2. Using `React.JSX`
=> fix(esm): fix exported types

esm/attributes-to-props.d.mts, esm/dom-to-react.d.mts, package-lock.json, package.json
fix: move `@types/react` to dependencies and fix esm types
Fixes #1313
Default import has return type of `any`
Default import has valid return type
=> fix: move `@types/react` to dependencies and fix esm types

esm/index.d.mts
Fix `any` type of export: 
Import:
```typescript
import HTMLReactParser from 'html-react-parser';
HTMLReactParser('');
```
Results in `any` typed `HTMLReactParser` reference that is disallowed by linters in many projects:
```
Unsafe call of an `any` typed value.eslint[@typescript-eslint/no-unsafe-call](https://typescript-eslint.io/rules/no-unsafe-call)
```
The export is not typed (i.e. `any`).
The export type is fixed to the expected one.
=> fix(esm): fix any type

package-lock.json, package.json
fix(package): set dependency `@types/react` to 17 or 18
Fixes #1320
`@types/react` is set to `18.2.55`
`@types/react` is set to `17 || 18`
=> fix(package): set dependency `@types/react` to 17 or 18

package-lock.json, package.json
build(package): make `@types/react` an optional peerDependency
Release-As: 5.1.8
`@types/react` is a required dependency
`@types/react` is an optional peerDependency
=> build(package): make @types/react an optional peerDependency

package.json
build(peer-deps): match allowed peer dependency ranges of `react` and `@types/react`
Fixes #1462
=> build(package): match allowed peer dependency ranges of react and @types/react

package-lock.json, package.json, rollup.config.mjs
See rollup/plugins#1783
Closes https://github.com/rollup/plugins/discussions/1777
```
@rollup/plugin-typescript  11.1.6  →  12.1.1
rollup                     4.24.4  →  4.25.0
```
Rollup build fails with error:
```
[!] (plugin typescript) RollupError: [plugin typescript] @rollup/plugin-typescript: Path of Typescript compiler option 'outDir' must be located inside the same directory as the Rollup 'file' option.
```
Updated `rollup.config.mjs`:
```js
plugins: [
typescript({
compilerOptions: {
outDir: 'dist',
},
],
```
=> build(rollup): allow for files to be nested in folders within outDir

package-lock.json, package.json
build(package): bump react and react-dom from 18.3.1 to 19.1.0
Fix Jest snapshots with `react-is` overrides: https://github.com/jestjs/jest/issues/15402#issuecomment-2575408173
See #1629
package.json devDependencies using `react` and `react-dom` v18
package.json devDependencies using `react` and `react-dom` v19
=> build(package): bump react and react-dom from 18.3.1 to 19.1.0
