remarkablemark/html-react-parser

- .npmignore
- .travis.yml
- package.json
Resolves #3
Continuous integration tool will run tests and linter and ensure code confidence.
- Update `package.json`:
- In **devDependencies**, specify wildcard for `react` and `react-dom` to allow latest versions to be installed (this ensures Travis runs tests with the latest version)
- In **peerDependencies**, specify `react` version `>=0.14` in order to stay consistent with React elements schema
- Ignore `.travis.yml` in `.npmignore`
> Add Travis CI

- .npmignore
- index.js
- package.json
Resolves #6
- Make the package compatible with UMD (Universal Module Definition)
- CommonJS
- AMD (RequireJS)
- `<script>` tag
- Ignore `lib/html-to-dom-server.js` when bundling for the browser
- Fix bugs and errors
- Update `.npmignore`
> UMD compatibility

- .travis.yml
- README.md
Adding some sweet badges to `README.md`.
> Update README with Travis and Coveralls badges

- .npmignore
- examples/requirejs.html
- examples/script-tag.html
- Create `examples` directory
- Create `./examples/script-tag.html` that demonstrates loading the parser with a script tag
- Create `./examples/requirejs.html` that demonstrates loading the parser with [Require.js](http://requirejs.org)
- Add `examples` to `.npmignore`
> Add examples

- README.md
- Update `README.md`:
- Reword beginning description
- Add installation instruction using CDN
- Update usage examples
- Refactor to ES6, JSX, and simplify
- Link to examples (#26)
- Update replace options
- Refactor simple and advanced examples to ES6, JSX, and simplify
> Tidy README instructions and examples

- package.json
- webpack.config.js
- Upgrade dependencies:
- html-dom-parser@0.1.1
- Upgrade devDependencies:
- eslint@4.1.1
- webpack@3.0.0
- Enable scope hoisting for webpack
> Upgrade dependencies (html-dom-parser@0.1.1)

- .travis.yml
- package.json
- webpack.config.js
> Update build and dependencies

- package.json
Fixes install warning:
```
html-react-parser > react-dom-core@0.0.3" has unmet peer dependency "fbjs@*".
html-react-parser > react-dom-core@0.0.3" has unmet peer dependency "object-assign@*".
```
Closes remarkablemark/react-dom-core#3
> chore(package): upgrade react-dom-core@0.0.4

- .travis.yml
- package.json
- types/index.d.ts
- types/test.tsx
- types/tsconfig.json
- Make `build` script work on Windows
Add TypeScript definitions
Resolves #95
> chore(typescript): add definitions

- README.md
- package.json
> build(package): update react-dom-core@0.1.1

- index.js
- test/html-to-react.js
> fix(index): add default export for parser

- test/__snapshots__/attributes-to-props.test.js.snap
- test/__snapshots__/dom-to-react.test.js.snap
- test/attributes-to-props.test.js
- test/dom-to-react.test.js
- test/html-to-react.test.js
- test/utilities.test.js
test: refactor tests
Tests lack organization and clarity. Not using snapshots.
Tests are better organized with better describe messages. Using snapshot tests.
> test: refactor tests and add snapshots

- lib/attributes-to-props.js
- lib/utilities.js
- test/__snapshots__/utilities.test.js.snap
- test/attributes-to-props.test.js
- test/utilities.test.js
refactor(utilities): create `setStyleProp` helper from `styleToJS`, add tests
> refactor(utilities): create `setStyleProp` helper from `styleToJS`

- lib/dom-to-react.js
- test/dom-to-react.test.js
refactor(dom-to-react): rename function, tidy module, add tests
> refactor(dom-to-react): rename function, tidy module, add tests

- package.json
Forgot to add `index.mjs` to `files` in `package.json` in #210 so this didn't end up in the published NPM package.
> fix(package): add missing file to package.json files

- examples/webpack/index.html
- examples/webpack/package.json
- examples/webpack/src/index.js
Add webpack v5 example which reproduces bug from #210. See #213 and #214.
> chore(examples): add webpack example

- .github/workflows/build.yml
- package.json
- test/module/index.mjs
test(module): write ES module unit test
No ES module unit test.
ES module unit test.
> test(module): write ES module unit test

- .github/workflows/build.yml
- .github/workflows/size-limit.yml
ci(github): timeout jobs after 5 min, cache node modules, and name steps for `build.yml` and `size-limit.yml`
> ci(github): timeout jobs after 5 min, cache node modules, & name steps

- .github/workflows/release.yml
ci(github): add workflow `release.yml`
Manual release/publish
Automated release/publish with [Release Please](https://github.com/googleapis/release-please)
> ci(github): add workflow `release.yml`

- .github/workflows/build.yml
- README.md
ci(github): replace Coveralls with Codecov in workflow `build.yml`
Coveralls
Codecov
> ci(github): replace Coveralls with Codecov in workflow `build.yml`

- README.md
david-dm.org no longer available
https://github.com/alanshaw/david/issues/179
david-dm.org no longer available
> remove david-dm badge

- .size-limit.json
- package.json
build(package): upgrade domhandler@4.3.1 and html-dom-parser@1.1.1
```
domhandler       4.3.0  →  4.3.1
html-dom-parser  1.1.0  →  1.1.1
```
- [domhandler@4.3.0](https://github.com/fb55/domhandler/releases/tag/v4.3.0)
- [html-dom-parser@1.1.0](https://github.com/remarkablemark/html-dom-parser/releases/tag/v1.1.0)
- [domhandler@4.3.0](https://github.com/fb55/domhandler/releases/tag/v4.3.1)
- [html-dom-parser@1.1.1](https://github.com/remarkablemark/html-dom-parser/releases/tag/v1.1.1)
> build(package): upgrade domhandler@4.3.1 and html-dom-parser@1.1.1

- package.json
build(package): add support for [React 18](https://reactjs.org/blog/2022/03/29/react-v18.html)
```
react      17.0.2  →  18.0.0
react-dom  17.0.2  →  18.0.0
```
Support up to React 17
Support up to React 18
> build(package): add support for React 18

- test/types/error.tsx
- test/types/exports.tsx
- test/types/index.tsx
- test/types/options/htmlparser2.tsx
- test/types/options/library.tsx
- test/types/options/replace.tsx
- test/types/options/trim.tsx
- tsconfig.json
test(types): refactor dtslint tests
> test(types): refactor dtslint tests

- .size-limit.json
- package.json
build(package): bump style-to-js from 1.1.1 to 1.1.2
Release-As: 3.0.6
```
style-to-js   1.1.1  →  1.1.2
```
> build(package): bump style-to-js from 1.1.1 to 1.1.2

- src/attributes-to-props.ts
- src/dom-to-react.ts
- src/index.ts
Release-As: 5.0.2
Stricter management of constants and improved types.
There is no change in behavior.
There is no change in behavior.
> refactor(domToReact): refactoring  multiple types

- src/attributes-to-props.ts
- src/utilities.ts
Release-As: 5.0.4
I worked on improving `type` a bit more.
There is no change in behavior.
There is no change in behavior.
> refactor(type): improved attributes-to-props and utilities type

- src/attributes-to-props.ts
- src/dom-to-react.ts
- src/utilities.ts
Release-As: 5.0.5
@remarkablemark 👋
I worked on improving `type`, and more intuitive code.
There is no change in behavior.
There is no change in behavior.
> refactor: improved attributes-to-props, dom-to-react, utilities

- package-lock.json
- package.json
feat(package): add react 19 to package.json peerDependencies
Closes #1455
Closes #1501
package.json peerDependencies supports up to React version 18
package.json peerDependencies supports up to React version 19
https://react.dev/blog/2024/12/05/react-19
> feat(package): add react 19 to package.json peerDependencies
